name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build . -t my-wordpress-image
        docker tag my-wordpress-image:latest ${DOCKER_HUB_USERNAME}/chuyen-de-cnpm:latest
        docker push ${DOCKER_HUB_USERNAME}/my-wordpress-image:latest

    - name: Deploy to Docker
      run: |
        docker-compose down
        docker-compose up -d
