name: Deploy WordPress

on:
  push:
    branches:
      - main  # Thay đổi branch nếu cần

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          --exclude '.git*' \
          --exclude 'node_modules' \
          ./ username@your_server:/path/to/your/wordpress/directory

      - name: Set permissions
        run: |
          ssh username@your_server "chown -R www-data:www-data /path/to/your/wordpress/directory"
